// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantOrderingApp.Data;

#nullable disable

namespace RestaurantOrderingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408115826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RestaurantOrderingApp.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Coffee",
                            Description = "",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Coffee",
                            Description = "",
                            IsAvailable = true,
                            Name = "Machiato",
                            Price = 90m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            Description = "",
                            IsAvailable = true,
                            Name = "Cappuchino",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Beverages",
                            Description = "",
                            IsAvailable = true,
                            Name = "Coca Cola",
                            Price = 90m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Beverages",
                            Description = "",
                            IsAvailable = true,
                            Name = "Fanta",
                            Price = 90m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Beverages",
                            Description = "",
                            IsAvailable = true,
                            Name = "Sprite",
                            Price = 90m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Beverages",
                            Description = "",
                            IsAvailable = true,
                            Name = "Rosa",
                            Price = 80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Beverages",
                            Description = "",
                            IsAvailable = true,
                            Name = "Rosa gazirana",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("RestaurantOrderingApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantOrderingApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantOrderingApp.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantOrderingApp.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantOrderingApp.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
